services:
  - type: web
    name: ld-sidecar-proxy
    env: docker
    repo: https://github.com/Linsars/glados-discourse-bot
    dockerfilePath: sidecar/Dockerfile
    dockerContext: sidecar
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "3000"
